// // Supabaseの設定
const SUPABASE_URL = 'https://lmfjebldqlwmacpgbqhm.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZmplYmxkcWx3bWFjcGdicWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMDE4NDgsImV4cCI6MjA1MjU3Nzg0OH0.pDiVIsx6dFNMzvIRMWSVHwxh5T86fxuGdtPB49dyZr4';